package space.narrate.words.android.ui.details

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.LinearLayout
import androidx.recyclerview.widget.AsyncDifferConfig
import androidx.recyclerview.widget.AsyncListDiffer
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListUpdateCallback
import space.narrate.words.android.data.disk.mw.WordAndDefinitions
import space.narrate.words.android.data.firestore.users.User
import java.lang.IllegalArgumentException

/**
 * An adapter that handles the addition, removal, moving and changing of views inside a
 * LinearLayout.
 */
class MerriamWebsterListAdapter(
        private val container: LinearLayout,
        private val listener: Listener
): ListUpdateCallback {

    interface Listener {
        fun onRelatedWordClicked(word: String)
        fun onDetailsButtonClicked()
        fun onDismissButtonClicked()
    }

    private val differ = AsyncListDiffer(
            this,
            AsyncDifferConfig.Builder(DIFF_CALLBACK).build()
    )

    /**
     * Change the currently displayed list of item, for the items which will be generated by
     * [MerriamWebsterList.generate].
     *
     * This method will diff the current and newly generated list and update the container's views
     * as needed.
     */
    fun submit(entries: List<WordAndDefinitions>, user: User?) {
        differ.submitList(MerriamWebsterList.generate(entries, user))
    }

    private fun getItem(position: Int): MerriamWebsterListItem {
        return differ.currentList[position]
    }

    private fun getViewType(position: Int): Int {
        return when (getItem(position)) {
            is MerriamWebsterListItem.PartOfSpeech -> VIEW_TYPE_PART_OF_SPEECH
            is MerriamWebsterListItem.Definition -> VIEW_TYPE_DEFINITION
            is MerriamWebsterListItem.Related -> VIEW_TYPE_RELATED
            is MerriamWebsterListItem.PermissionPane -> VIEW_TYPE_PERMISSION_PANE
        }
    }

    private fun onBindView(view: View, item: MerriamWebsterListItem) {
        when (item) {
            is MerriamWebsterListItem.PartOfSpeech ->
                MerriamWebsterListItemBinder.PartOfSpeechBinder.bind(view, item, listener)
            is MerriamWebsterListItem.Definition ->
                MerriamWebsterListItemBinder.DefinitionBinder.bind(view, item, listener)
            is MerriamWebsterListItem.Related ->
                MerriamWebsterListItemBinder.RelatedBinder.bind(view, item, listener)
            is MerriamWebsterListItem.PermissionPane ->
                MerriamWebsterListItemBinder.PermissionPaneBinder.bind(view, item, listener)
        }
    }

    private fun onCreateView(parent: ViewGroup, viewType: Int): View {
        return LayoutInflater.from(parent.context).inflate(when (viewType) {
            VIEW_TYPE_PART_OF_SPEECH -> MerriamWebsterListItemBinder.PartOfSpeechBinder.layout
            VIEW_TYPE_DEFINITION -> MerriamWebsterListItemBinder.DefinitionBinder.layout
            VIEW_TYPE_RELATED -> MerriamWebsterListItemBinder.RelatedBinder.layout
            VIEW_TYPE_PERMISSION_PANE -> MerriamWebsterListItemBinder.PermissionPaneBinder.layout
            else -> throw IllegalArgumentException("Unsupported view type = [$viewType]")
        }, parent, false)
    }

    override fun onChanged(position: Int, count: Int, payload: Any?) {
        (position until (position + count)).forEach { i ->
            onBindView(container.getChildAt(i), getItem(i))
        }
    }

    override fun onMoved(fromPosition: Int, toPosition: Int) {
        container.apply {
            val view = getChildAt(fromPosition)
            removeViewAt(fromPosition)
            addView(view, toPosition)
        }
    }

    override fun onInserted(position: Int, count: Int) {
        (position until (position + count)).forEach { i ->
            val view = onCreateView(container, getViewType(i))
            onBindView(view, getItem(i))
            container.addView(view, i)
        }
    }

    override fun onRemoved(position: Int, count: Int) {
        ((position + count - 1) downTo position).forEach { i ->
            container.removeViewAt(i)
        }
    }

    companion object {
        private const val VIEW_TYPE_PART_OF_SPEECH = 0
        private const val VIEW_TYPE_DEFINITION = 1
        private const val VIEW_TYPE_RELATED = 2
        private const val VIEW_TYPE_PERMISSION_PANE = 3

        private val DIFF_CALLBACK = object : DiffUtil.ItemCallback<MerriamWebsterListItem>() {
            override fun areItemsTheSame(
                    oldItem: MerriamWebsterListItem,
                    newItem: MerriamWebsterListItem
            ): Boolean {
                return oldItem.isSameAs(newItem)
            }

            override fun areContentsTheSame(
                    oldItem: MerriamWebsterListItem,
                    newItem: MerriamWebsterListItem
            ): Boolean {
                return oldItem.isContentSameAs(newItem)
            }
        }
    }

}